### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by mtruongle** [ttbrunner/alphasheep#3]
Update Readme by requirements and starting procedures.

**Comment by ttbrunner** [comment]
Technically, the readme contains this information. What are you looking for specifically?

Anyway, I'm currently reworking the training procedure (to have parallel simulation workers) in #2. So I'll add a training guide as well. Unfortunately, distributed training might not make things simpler :smile:

**Comment by mtruongle** [comment]
Oh nice. Overlooked it :D I just want to play around with it :)
